services:
  - type: web
    name: aero-world
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 24
      - key: DATABASE_URL
        sync: false
      - key: ADMIN_EMAILS
        sync: false
